name: opentyrian
version: 'trunk'
license: GPL-2.0+
summary: An arcade-style shoot 'em up
description: >
  OpenTyrian is a port of the DOS shoot-em-up Tyrian.

  Tyrian is an arcade-style vertical scrolling shooter. The story is set in
  20,031 where you play as Trent Hawkins, a skilled fighter-pilot employed to
  fight Microsol and save the galaxy.

grade: stable
confinement: strict
base: core22
compression: lzo

apps:
  opentyrian:
    command: bin/tyrian-launch
    command-chain: [bin/desktop-launch]
    desktop: usr/local/share/applications/opentyrian.desktop
    plugs:
    - audio-playback
    - desktop
    - desktop-legacy
    - joystick
    - network
    - network-bind
    - opengl
    - pulseaudio
    - screen-inhibit-control
    - wayland
    - x11

parts:
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  launcher:
    source: scripts
    plugin: dump
    organize:
      tyrian-launch: bin/tyrian-launch

  tyrian:
    after: [desktop-glib-only]
    source: https://github.com/opentyrian/opentyrian.git
    plugin: make
    override-pull: |
      craftctl default
      sed -i 's|Icon=.*|Icon=/usr/local/share/icons/tyrian-128.png|' linux/opentyrian.desktop
    override-build: |
      craftctl default
      install -m644 -D -t $CRAFT_PART_INSTALL/usr/local/share/applications linux/opentyrian.desktop
      install -m644 -D -t $CRAFT_PART_INSTALL/usr/local/share/icons linux/icons/tyrian-128.png
    build-packages:
    - gcc
    - libsdl2-net-dev
    - libsdl2-dev
    stage-packages:
    - curl
    - freeglut3
    - libdrm2
    - libgl1
    - libglapi-mesa
    - libglu1-mesa
    - libsdl2-net-2.0-0
    - libsdl2-2.0-0
    - libslang2
    - libx11-xcb1
    - libxcb-dri2-0
    - libxcb-dri3-0
    - libxcb-glx0
    - libxcb-present0
    - libxcb-sync1
    - libxdamage1
    - libxfixes3
    - libxshmfence1
    - libxxf86vm1
    - unzip
    prime:
    - usr/bin/curl
    - usr/bin/unzip
    - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    - usr/local
